### PR TITLE
docs: release doc basics

### PR DESCRIPTION
**Pull request by p0mvn**
This documents SQS release process and rules around versioning

### CODE REVIEW

**Review by cryptomatictrader — COMMENTED** [review]
Thanks for summarizing it in the doc!

One thing I'm unsure is: what is the criteria for incrementing the rc number only?

**Comment by p0mvn** [comment]
> Thanks for summarizing it in the doc!
> 
> One thing I'm unsure is: what is the criteria for incrementing the rc number only?

Good point.

The rc numbers should be incremented for any changes that occur in staging and before getting to production.

Let's say that we plan a release, and the current version is `v0.18.5`. Then, we tag a `v0.18.-6-rc0` and push it to the stage for testing. QA uncovers a bug during stage testing. We push a fix, incrementing the rc number for a new stage tag - `v0.18.6-rc1`. Now, the stage QA passes, and we proceed to production with `v0.18.6`.

I will update the document with this context. Let me know what you think

**Comment by p0mvn** [comment]
@cryptomatictrader updated docs. This is ready for a final review/ACK

**Comment by cryptomatictrader** [comment]
Sorry for the review delay. Looks good to me! I'll also fill it in if I run into anything additional. Thanks!

**Pull request merged**
